[tool.pylint.master]
ignore = 'tests, alembic, venv, kuber, containers, scripts'

[tool.pylint.message_control]
disable = ['missing-module-docstring', 'missing-function-docstring', 'missing-class-docstring', 'too-few-public-methods', 'fixme', 'unused-argument', 'duplicate-code', 'R0914', 'R0913', 'R0912']
extension-pkg-whitelist = "pydantic, lxml"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.basic]
argument-rgx = '[a-z0-9_]{2,30}$'
variable-rgx = '[a-zA-Z0-9_]{2,30}$'
good-names = ['i', 'j', 'k', 'v', 'ex', 'Run', '_']

[tool.pylint.options]
jobs = 4
disable = ['missing-module-docstring', 'missing-function-docstring', 'missing-class-docstring', 'too-few-public-methods', 'unused-argument','fixme',  'duplicate-code', 'R0914', 'R0913','R0912']

[tool.pylint.design]
max-args = 9
max-locals = 20

[tool.isort]
skip = "alembic, venv, kuber, containers, scripts"
profile = "black"
line_length = 120
lines_after_imports = 2
force_sort_within_sections = true

[tool.mypy]
ignore_missing_imports = true
strict = true
warn_return_any = false
disallow_untyped_calls = false
disallow_subclassing_any = false
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
exclude = 'tests'

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true

[[tool.mypy.overrides]]
module = "src.main"
disallow_untyped_decorators = false

[tool.black]
line-length = 120
target-version = ['py311']

[tool.pytest.ini_options]
log_cli = true
filterwarnings = ["ignore:SelectableGroups dict interface is deprecated. Use select.:DeprecationWarning"]
