"""add_xlsid_mainmenu

Revision ID: 55c88c6f38e2
Revises: 614761ca392e
Create Date: 2023-08-16 07:44:31.513727

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '55c88c6f38e2'
down_revision = '614761ca392e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_menu', sa.Column('id_xls', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_menu', 'id_xls')
    # ### end Alembic commands ###
