"""add_uq

Revision ID: 614761ca392e
Revises: 6af8da0b87f0
Create Date: 2023-08-12 17:17:01.211492

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '614761ca392e'
down_revision = '6af8da0b87f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_dishes_title', 'dishes', ['title'])
    op.create_unique_constraint('uq_sub_menu_title', 'sub_menu', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sub_menu_title', 'sub_menu', type_='unique')
    op.drop_constraint('uq_dishes_title', 'dishes', type_='unique')
    # ### end Alembic commands ###
