"""create_uq

Revision ID: 6af8da0b87f0
Revises: da7635bb9cc3
Create Date: 2023-08-12 16:47:05.209484

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '6af8da0b87f0'
down_revision = 'da7635bb9cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_main_menu_title', 'main_menu', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_main_menu_title', 'main_menu', type_='unique')
    # ### end Alembic commands ###
