"""add_id_xls_to_constraint

Revision ID: 8bb9f9642fc8
Revises: 55c88c6f38e2
Create Date: 2023-08-16 12:21:03.959958

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '8bb9f9642fc8'
down_revision = '55c88c6f38e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_main_menu_title', 'main_menu', type_='unique')
    op.create_unique_constraint('uq_main_menu_id_xls', 'main_menu', ['id_xls'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_main_menu_id_xls', 'main_menu', type_='unique')
    op.create_unique_constraint('uq_main_menu_title', 'main_menu', ['title'])
    # ### end Alembic commands ###
