"""add_id_xls_to_submenu_n_dishes

Revision ID: b18c978633d6
Revises: 8bb9f9642fc8
Create Date: 2023-08-16 13:06:35.416513

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b18c978633d6'
down_revision = '8bb9f9642fc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('id_xls', sa.String(), nullable=True))
    op.drop_constraint('uq_dishes_title', 'dishes', type_='unique')
    op.create_unique_constraint('uq_dish_id_xls', 'dishes', ['id_xls'])
    op.add_column('sub_menu', sa.Column('id_xls', sa.String(), nullable=True))
    op.drop_constraint('uq_sub_menu_title', 'sub_menu', type_='unique')
    op.create_unique_constraint('uq_sub_menu_id_xls', 'sub_menu', ['id_xls'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sub_menu_id_xls', 'sub_menu', type_='unique')
    op.create_unique_constraint('uq_sub_menu_title', 'sub_menu', ['title'])
    op.drop_column('sub_menu', 'id_xls')
    op.drop_constraint('uq_dish_id_xls', 'dishes', type_='unique')
    op.create_unique_constraint('uq_dishes_title', 'dishes', ['title'])
    op.drop_column('dishes', 'id_xls')
    # ### end Alembic commands ###
