"""add_field_to_sub_menu

Revision ID: c2e770790ee2
Revises: bf2d493cb2c0
Create Date: 2023-07-23 13:33:14.415297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e770790ee2'
down_revision = 'bf2d493cb2c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_menu', sa.Column('title', sa.String(), nullable=False))
    op.add_column('sub_menu', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('sub_menu', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_menu', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sub_menu', 'description')
    op.drop_column('sub_menu', 'title')
    # ### end Alembic commands ###
