"""cascade_delete

Revision ID: da7635bb9cc3
Revises: 6d3f38970b59
Create Date: 2023-07-23 15:07:06.343187

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'da7635bb9cc3'
down_revision = '6d3f38970b59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dishes_sub_menu_id_fkey', 'dishes', type_='foreignkey')
    op.create_foreign_key(None, 'dishes', 'sub_menu', [
                          'sub_menu_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sub_menu_main_menu_id_fkey',
                       'sub_menu', type_='foreignkey')
    op.create_foreign_key(None, 'sub_menu', 'main_menu', [
                          'main_menu_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_menu', type_='foreignkey')
    op.create_foreign_key('sub_menu_main_menu_id_fkey',
                          'sub_menu', 'main_menu', ['main_menu_id'], ['id'])
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.create_foreign_key('dishes_sub_menu_id_fkey',
                          'dishes', 'sub_menu', ['sub_menu_id'], ['id'])
    # ### end Alembic commands ###
